### ISSUE TITLE
Error while running the train scripts.

### ISSUE THREAD

**Issue by fsxq** [saic-vul/iterdet#14]
Thanks for your great work.
I meet this error while running the train scripts.

**Reproduction**
What command or script did you run?
```
bash tools/dist_train.sh configs/iterdet/wider_person_faster_rcnn_r50_fpn_2x.py 1
```

**Environment**

sys.platform: linux
Python: 3.7.7 (default, May  7 2020, 21:25:33) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce RTX 2080 Ti
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
TorchVision: 0.7.0
OpenCV: 4.3.0
MMCV: 0.5.8
MMDetection: 2.0.0+b293300
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1

**Error traceback**
```
2020-07-30 20:57:45,185 - mmdet - INFO - Epoch [1][7950/7981]	lr: 0.00010, eta: 7:51:08, time: 0.160, data_time: 0.004, memory: 8025, loss_rpn_cls: 0.0383, loss_rpn_bbox: 0.0440, loss_cls: 0.1850, acc: 92.5312, loss_bbox: 0.2831, loss: 0.5503
[                                                  ] 0/1000, elapsed: 0s, ETA:/home/n-n/iterdet/mmdet/core/post_processing/bbox_nms.py:44: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629403081/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  labels = valid_mask.nonzero()[:, 1]
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1000/1000, 7.5 task/s, elapsed: 133s, ETA:     0s

Traceback (most recent call last):
  File "tools/train.py", line 159, in <module>
    main()
  File "tools/train.py", line 155, in main
    meta=meta)
  File "/home/n-n/iterdet/mmdet/apis/train.py", line 165, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/site-packages/mmcv-0.5.8-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 384, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/site-packages/mmcv-0.5.8-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 293, in train
    self.call_hook('after_train_epoch')
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/site-packages/mmcv-0.5.8-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 245, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/n-n/iterdet/mmdet/core/evaluation/eval_hooks.py", line 74, in after_train_epoch
    self.evaluate(runner, results)
  File "/home/n-n/iterdet/mmdet/core/evaluation/eval_hooks.py", line 32, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/n-n/iterdet/mmdet/datasets/crowd_human.py", line 87, in evaluate
    pr = brambox.stat.pr(predicted_df, true_df, iou_thr)
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/site-packages/brambox-3.0.0-py3.7-linux-x86_64.egg/brambox/stat/_pr.py", line 51, in pr
    det = match_det(det, anno, threshold, criteria=crit, class_label=label, ignore=2 if ignore else 0)
  File "brambox/stat/_matchboxes.pyx", line 129, in brambox.stat._matchboxes.match_det
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/site-packages/brambox-3.0.0-py3.7-linux-x86_64.egg/brambox/util/_dualgroupby.py", line 47, in __init__
    self.df1 = {col: np_col(df1, col) for col in df1.columns}
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/site-packages/brambox-3.0.0-py3.7-linux-x86_64.egg/brambox/util/_dualgroupby.py", line 47, in <dictcomp>
    self.df1 = {col: np_col(df1, col) for col in df1.columns}
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/site-packages/brambox-3.0.0-py3.7-linux-x86_64.egg/brambox/util/_pd.py", line 147, in np_col
    return bm.blocks[bm._blknos[idx]].iget(bm._blklocs[idx])
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/n-n/anaconda3/envs/iterdet/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/n-n/anaconda3/envs/iterdet/bin/python', '-u', 'tools/train.py', '--local_rank=0', 'configs/iterdet/wider_person_faster_rcnn_r50_fpn_2x.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
```

**Comment by filaPro** [comment]
Hi @fsxq,

Looks like `brambox==3.0.0` is not capable with latest `pandas==1.1.0`. I've fixed `pandas==1.0.0` in [f8a3b4f](https://github.com/saic-vul/iterdet/commit/f8a3b4fb9ae4c4ffe3462944bd9b18812682eddc).

Can you try and say if it helped?

**Comment by fsxq** [comment]
Thanks a lot. I reinstalled pandas==1.0.0 and it works. 🤭

**Comment by hyz0720** [comment]
Excuse me, I also ran on a single 2080ti, the video memory will burst in the middle of the run, do you have this situation?
