### ISSUE TITLE
'IterDetFasterRCNN is not in the detector registry'

### ISSUE THREAD

**Issue by melih1996** [saic-vul/iterdet#26]
When I run webcam_demo.py I got the error below:
Traceback (most recent call last):
  File "webcam_demo.py", line 46, in <module>
    main()
  File "webcam_demo.py", line 28, in main
    model = init_detector(args.config, args.checkpoint, device=device)
  File "/home/melih/anaconda3/envs/ai/lib/python3.8/site-packages/mmdet/apis/inference.py", line 34, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/home/melih/anaconda3/envs/ai/lib/python3.8/site-packages/mmdet/models/builder.py", line 67, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/melih/anaconda3/envs/ai/lib/python3.8/site-packages/mmdet/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/melih/anaconda3/envs/ai/lib/python3.8/site-packages/mmcv/utils/registry.py", line 163, in build_from_cfg
    raise KeyError(
KeyError: 'IterDetFasterRCNN is not in the detector registry'

**Comment by filaPro** [comment]
Hi @melih1996,

I think, you missed something during installation. Can you pease check #6 and #10 ?
