### ISSUE TITLE
Iterdet to TorchScript

### ISSUE THREAD

**Issue by rh-ia** [saic-vul/iterdet#31]
Dear authors of Iterdet,

Thanks for the extensive README's, this has been helpful.

I had a question concerning saving a quantized model to torchscript for mobile deployment, is this possible?

For now I am stuck with:

```
import os
import torch

def print_model_size(mdl):
    torch.save(mdl.state_dict(), "tmp.pt")
    print("%.2f MB" %(os.path.getsize("tmp.pt")/1e6))
    os.remove('tmp.pt')


model = init_detector(config, checkpoint, device='cpu')
model.eval()
backend = "qnnpack"
model.qconfig = torch.quantization.get_default_qconfig(backend)
print("Model: ")
print_model_size(model)
torch.backends.quantized.engine = backend
model_static_quantized = torch.quantization.prepare(model, inplace=False)
model_static_quantized = torch.quantization.convert(model_static_quantized, inplace=False)
print("Quantized Model: ")
print_model_size(model_static_quantized)

# Use either the script or trace method to convert the quantized model to the TorchScript format:
torchscript_model = torch.jit.script(model)
# Then optimize the TorchScript formatted model for mobile and save it:
from torch.utils.mobile_optimizer import optimize_for_mobile
torchscript_model_optimized = optimize_for_mobile(torchscript_model)
torch.jit.save(torchscript_model_optimized, os.path.split(checkpoint)[0]+'/latest_torchscript.pt')
```
Which results in:
```
NotSupportedError                         Traceback (most recent call last)
<ipython-input-47-41427ee174f2> in <module>()
      1 # Use either the script or trace method to convert the quantized model to the TorchScript format:
----> 2 torchscript_model = torch.jit.script(model)
      3 # dummy_input = torch.rand(1, 3, 224, 224)
      4 # torchscript_model = torch.jit.trace(model, dummy_input)
      5 # Then optimize the TorchScript formatted model for mobile and save it:

8 frames
/usr/local/lib/python3.7/site-packages/torch/jit/_script.py in script(obj, optimize, _frames_up, _rcb)
    896     if isinstance(obj, torch.nn.Module):
    897         return torch.jit._recursive.create_script_module(
--> 898             obj, torch.jit._recursive.infer_methods_to_compile
    899         )
    900 

/usr/local/lib/python3.7/site-packages/torch/jit/_recursive.py in create_script_module(nn_module, stubs_fn, share_types)
    350     check_module_initialized(nn_module)
    351     concrete_type = get_module_concrete_type(nn_module, share_types)
--> 352     return create_script_module_impl(nn_module, concrete_type, stubs_fn)
    353 
    354 def create_script_module_impl(nn_module, concrete_type, stubs_fn):

/usr/local/lib/python3.7/site-packages/torch/jit/_recursive.py in create_script_module_impl(nn_module, concrete_type, stubs_fn)
    362     """
    363     cpp_module = torch._C._create_module_with_type(concrete_type.jit_type)
--> 364     method_stubs = stubs_fn(nn_module)
    365     property_stubs = get_property_stubs(nn_module)
    366 

/usr/local/lib/python3.7/site-packages/torch/jit/_recursive.py in infer_methods_to_compile(nn_module)
    589     stubs = []
    590     for method in uniqued_methods:
--> 591         stubs.append(make_stub_from_method(nn_module, method))
    592     return overload_stubs + stubs
    593 

/usr/local/lib/python3.7/site-packages/torch/jit/_recursive.py in make_stub_from_method(nn_module, method_name)
     50     # In this case, the actual function object will have the name `_forward`,
     51     # even though we requested a stub for `forward`.
---> 52     return make_stub(func, method_name)
     53 
     54 

/usr/local/lib/python3.7/site-packages/torch/jit/_recursive.py in make_stub(func, name)
     35 def make_stub(func, name):
     36     rcb = _jit_internal.createResolutionCallbackFromClosure(func)
---> 37     ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
     38     return ScriptMethodStub(rcb, ast, func)
     39 

/usr/local/lib/python3.7/site-packages/torch/jit/frontend.py in get_jit_def(fn, def_name, self_name)
    219             arg.annotation = unused_def.args.args[0].annotation
    220 
--> 221     return build_def(ctx, fn_def, type_line, def_name, self_name=self_name)
    222 
    223 

/usr/local/lib/python3.7/site-packages/torch/jit/frontend.py in build_def(ctx, py_def, type_line, def_name, self_name)
    241                        py_def.col_offset,
    242                        py_def.col_offset + len("def"))
--> 243     param_list = build_param_list(ctx, py_def.args, self_name)
    244     return_type = None
    245     if getattr(py_def, 'returns', None) is not None:

/usr/local/lib/python3.7/site-packages/torch/jit/frontend.py in build_param_list(ctx, py_args, self_name)
    264         expr = py_args.kwarg
    265         ctx_range = ctx.make_range(expr.lineno, expr.col_offset - 1, expr.col_offset + len(expr.arg))
--> 266         raise NotSupportedError(ctx_range, _vararg_kwarg_err)
    267     if py_args.vararg is not None:
    268         expr = py_args.vararg

NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/content/drive/MyDrive/IA_Main/Projecten/Wel_gevallen/Ahold_Delhaize/4.Consultants_work/iterdet-master/mmdet/core/fp16/decorators.py", line 138
    @auto_fp16(apply_to=('img', ))
    def forward(self, img, img_metas, return_loss=True, **kwargs):
                                                         ~~~~~~~ <--- HERE
        """
        Calls either forward_train or forward_test depending on whether
```

Details on Config:
```
# model settings
model = dict(
    type='IterDetRetinaNet',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs=True,
        num_outs=5,
        norm_cfg=dict(type='BN')),
    bbox_head=dict(
        type='RetinaHead',
        num_classes=4,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 1.5, 2.0, 2.5, 3.0],
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0),
        final_crop=False
    ))
# training and testing settings
train_cfg = dict(
    assigner=dict(
        type='MaxIoUAssigner',
        pos_iou_thr=0.5,
        neg_iou_thr=0.4,
        min_pos_iou=0,
        ignore_iof_thr=0.5),
    allowed_border=-1,
    pos_weight=-1,
    debug=False)
test_cfg = dict(
    nms_pre=2000,
    min_bbox_size=0,
    score_thr=0.1,
    nms=dict(type='nms', iou_thr=0.4),
    max_per_img=1000,
    n_iterations=2)
# dataset settings
dataset_type = 'CocoDataset'

classes = ('sku_1', 'sku_2', 'sku_3', 'sku_4')
data_root = 'data/model/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=[(1000, 600), (1666, 1000)], keep_ratio=True, final_crop=False),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='AddHistory'),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'history', 'gt_bboxes', 'gt_labels', 'gt_bboxes_ignore']),
    # dict(type='Collect', keys=['img', 'history', 'gt_bboxes','gt_bboxes_ignore']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'annotations_TRAIN.json',
        img_prefix=data_root + 'Images/',
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'annotations_TEST.json',
        img_prefix=data_root + 'Images/',
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        classes=classes,
        ann_file=data_root + 'annotations_VALIDATE.json',
        img_prefix=data_root + 'Images/',
        pipeline=test_pipeline))
# optimizer
optimizer = dict(
    type='Adam',
    lr=.0001
)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(
    policy='step',
    step=[16, 22])
checkpoint_config = dict(interval=1)
evaluation = dict(interval=1)
# yapf:disable
log_config = dict(
    interval=20,
    hooks=[
        dict(type='TextLoggerHook'),
        # dict(type='TensorboardLoggerHook')
    ])
# yapf:enable
# runtime settings
total_epochs = 24
dist_params = dict(backend='nccl')
log_level = 'DEBUG'
work_dir = './work_dirs/iterdet/model_retinanet_r50_fpn_2x'
load_from = None
resume_from = None
workflow = [('train', 1)]
```
Details on Env:
```
{"env_info": "sys.platform: linux\nPython: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]\nCUDA available: True\nCUDA_HOME: /usr/local/cuda\nNVCC: Build cuda_11.0_bu.TC445_37.28845127_0\nGPU 0: Tesla P100-PCIE-16GB\nGCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0\nPyTorch: 1.7.1\nPyTorch compiling details: PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.0\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37\n  - CuDNN 8.0.5\n  - Magma 2.5.2\n  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, \n\nTorchVision: 0.8.2\nOpenCV: 4.5.1\nMMCV: 0.6.2\nMMDetection: 2.0.0+unknown\nMMDetection Compiler: GCC 7.5\nMMDetection CUDA Compiler: 11.0", "seed": null}
```

Any help would be greatly appreciated!

Kind regards,

Ruben

**Comment by filaPro** [comment]
Hi @rh-ia ,
I'm not familiar with torchscript. Looks like you are receiving this error because of `**kwargs` argument in `auto_fp16` decorator. As this decorator is unnecessarily in your case you should simply remove it. In case of `IterDerRetinaNet` i think it is in this [line](https://github.com/saic-vul/iterdet/blob/master/mmdet/models/detectors/base.py#L137).

**Comment by rh-ia** [comment]
Dear @filaPro,

Thanks a lot for your answer, indeed I received the error because TorchScript does not take variable amount of kwargs, furthermore constructing a ScriptModule through the `torch.jit.scipt` actually requires refactoring quite a bit of the code I realise... Instead I decided to try tracing via ONNX, which you facilitate through the script `tools/pytorch2onnx.py`.
Running this on a saved model gives me:
```
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 128, in <module>
    main()
  File "tools/pytorch2onnx.py", line 120, in main
    onnx_model = export_onnx_model(model, (input_data, ), args.passes)
  File "tools/pytorch2onnx.py", line 44, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/__init__.py", line 230, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 91, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 639, in _export
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 411, in _model_to_graph
    use_new_jit_passes)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 379, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.7/site-packages/torch/onnx/utils.py", line 342, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/_trace.py", line 1148, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/jit/_trace.py", line 130, in forward
    self._force_outplace,
  File "/usr/local/lib/python3.7/site-packages/torch/jit/_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/iterdet-master/mmdet/models/detectors/single_stage.py", line 58, in forward_dummy
    x = self.extract_feat(img)
TypeError: extract_feat() missing 1 required positional argument: 'history'
```
Maybe you would have an idea to add the the history here?

Best wishes,

Ruben

**Comment by filaPro** [comment]
Hi @rh-ia ,
Please refer to #21.
